name = "oj-website-api"
main = "workers/api/index.js"
compatibility_date = "2026-09-29"
workers_dev = true
minify = false

[observability.logs]
enabled = true

[vars]
API_VERSION = "2026-09-29"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "oj-website-media-3039fcee5"
preview_bucket_name = "oj-website-media-preview-3039fcee5"

[[d1_databases]]
binding = "DB"
database_name = "oj-website"
database_id = "15db100b-8dc4-4723-ba69-368ac602ad44"
migrations_dir = "db/migrations"
