#!/usr/bin/env python3
"""
build_galleries.py — generate assets/js/galleries.js from the on-disk shoot folders.

Scans the top-level portfolio folders at the repo root and writes a static JS
manifest (OJ_GALLERIES) that lists every real photo per collection, so the
homepage portfolio can be driven purely by the folders (one gallery per folder)
with no hard-coded tiles. Also emits OJ_HEROES (the real hero-image pool) and
OJ_ABOUT (the single about image) from the utility folders.

Usage:
    python3 tools/build_galleries.py          # run from the repo root

Metadata (title / category / blurb) is declared below; file lists are read
straight from each folder so a new photo dropped in a folder appears on rebuild.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root

# display order + editorial metadata for every gallery (one per shoot folder)
GALLERIES = [
    # id, folder, title, cat, blurb
    ("headshots-portfolio", "Headshots Portfolio", "Headshots Portfolio", "portraits",
     "Boardroom-ready and beyond — a wide run of professional portraits for teams, founders and everyone whose first impression matters."),
    ("headshots", "Headshots", "Headshots", "portraits",
     "Close-up, confident headshots in soft, sculpted light — made for profiles that need to say \u2018trust me\u2019 before you speak."),
    ("inductees", "Inductees", "Inductees", "portraits",
     "Dressed like champions — the 2am crowd caught mid-celebration at induction, ceremonial gown and all."),
    ("grad-induction", "Grad & Induction", "Grad & Induction", "portraits",
     "Graduation and induction milestones — hood, gown, handshake and the family pride around it."),
    ("style-all", "Style & All", "Style & All", "portraits",
     "Personal-branding portraits — style-first sessions for creators, professionals and people with a look."),
    ("birthdays", "Birthdays", "Birthdays", "portraits",
     "Cake-frost smiles and surprise-seconds — milestones celebrated exactly as they felt."),
    ("couples", "Couples", "Couples", "weddings",
     "Engagement and anniversary sessions for couples who laugh with their whole faces."),
    ("ayo-ola", "Ayo & Ola", "Ayo & Ola", "weddings",
     "Two families, one blessed afternoon — the vows, the fabric and the joy of Ayo & Ola."),
    ("crimson", "Crimson", "Crimson", "editorial",
     "A fine-art study in red — silk, skin and sculpted light."),
    ("arambara", "Arambara", "Arambara", "editorial",
     "A movement study in motion and stillness — fashion-forward frames for the bold."),
    ("light-dark", "Light & Dark", "Light & Dark", "editorial",
     "Chiaroscuro portraits where shadow does half the talking."),
    ("suit-boss", "Suit Boss", "Suit Boss", "editorial",
     "Tailoring as armour — a menswear editorial cut close to the bone."),
    ("brown-sugar", "Brown Sugar", "Brown Sugar", "editorial",
     "Warm tones, warm skin — an ode to deep browns in golden light."),
    ("editorial", "Editorial", "Editorial", "editorial",
     "A mixed editorial reel — attitude, wardrobe and negative space."),
    ("men-in-black", "Men in Black - The Red Carpet", "Men in Black: The Red Carpet", "events",
     "Red-carpet coverage for a night of suits, shutters and controlled chaos."),
    ("summerfest", "Westside Summerfest", "Westside Summerfest", "events",
     "Golden-hour performances and crowd swells — three stages, one festival, no missed beat."),
    ("blue-moon-gala", "Once in a Blue Moon Gala", "Once in a Blue Moon Gala", "events",
     "A rare night indeed — tables, toasts and the dance floor after midnight."),
    ("credo-hackathon", "Credo Hackathon", "Credo Hackathon", "events",
     "Forty-eight hours of builders — whiteboards, wireframes and the final-demo high five."),
    ("vmj-book-launch", "VMJ Book Launch", "VMJ Book Launch", "events",
     "Author, audience, applause — the launch of a literary dream, from green room to signing desk."),
    ("abh-merch", "ABH Merch Launch", "ABH Merch Launch", "commercial",
     "Product storytelling for a merch drop — every thread and tag in its best light."),
]

# galleries surfaced as the three large "Selected Work" frames (feature-1/2/3)
SHOWCASE = ["headshots-portfolio", "inductees", "crimson"]

UTIL = {
    "heroes": "Hero Images",   # becomes the rotating hero pool
    "about": "About Page",     # the single real about portrait
}


def image_files(folder):
    p = os.path.join(ROOT, folder)
    files = sorted(
        f for f in os.listdir(p)
        if os.path.isfile(os.path.join(p, f)) and f.lower().endswith(".jpg")
    )
    return [os.path.join(folder, f) for f in files]


def main():
    out = []
    out.append("/* AUTO-GENERATED by tools/build_galleries.py — do not edit by hand.")
    out.append("   The homepage portfolio is driven from the on-disk shoot folders.")
    out.append("   Regenerate with:  python3 tools/build_galleries.py  */")
    out.append("")
    out.append("window.OJ_GALLERIES = [")
    seen = set()
    for i, (gid, folder, title, cat, blurb) in enumerate(GALLERIES):
        files = image_files(folder)
        if not files:
            continue
        assert gid not in seen, "duplicate gallery id: " + gid
        seen.add(gid)
        obj = {
            "id": gid,
            "title": title,
            "cat": cat,
            "folder": folder,
            "desc": blurb,
            "files": files,
        }
        comma = "," if i < len(GALLERIES) - 1 else ""
        out.append(json.dumps(obj, ensure_ascii=False) + comma)
    out.append("];")
    out.append("")

    heroes = image_files(UTIL["heroes"])
    about = image_files(UTIL["about"])
    out.append("window.OJ_HEROES = " + json.dumps(heroes, ensure_ascii=False) + ";")
    out.append("window.OJ_ABOUT  = " + json.dumps(about[0] if about else "", ensure_ascii=False) + ";")
    out.append("window.OJ_SHOWCASE = " + json.dumps(SHOWCASE) + ";")
    out.append("")

    target = os.path.join(ROOT, "assets", "js", "galleries.js")
    with open(target, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")

    total = 0
    for _, folder, _t, _c, _b in GALLERIES:
        total += len(image_files(folder))
    print("wrote", target)
    print("galleries:", len(seen), "photos mapped:", total,
          "hero pool:", len(heroes), "about:", len(about))


if __name__ == "__main__":
    main()
